
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug  8 2025 23:41:02 EDT (Aug  9 2025 03:41:02 UTC)

// Verification Directory fv/complex_multiplier_top 

`timescale 1ns / 1ps

module complex_multiplier_top(clk, rst, start, a_r, a_i, b_r, b_i, p_r,
     p_i, done);
  input clk, rst, start;
  input [3:0] a_r, a_i, b_r, b_i;
  output signed [7:0] p_r, p_i;
  output done;
  wire clk, rst, start;
  wire [3:0] a_r, a_i, b_r, b_i;
  wire signed [7:0] p_r, p_i;
  wire done;
  wire [7:0] datapath_inst_pp1;
  wire [7:0] datapath_inst_pp2;
  wire [2:0] fsm_inst_current_state;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_99, n_100, n_101, n_102, n_103, n_104;
  wire n_105, n_106, n_107;
  SDFFRHQX1 \datapath_inst_p_i_reg_reg[7] (.RN (n_107), .CK (clk), .D
       (n_106), .SI (p_i[7]), .SE (n_105), .Q (p_i[7]));
  SDFFRHQX1 \datapath_inst_p_r_reg_reg[7] (.RN (n_107), .CK (clk), .D
       (n_106), .SI (p_r[7]), .SE (n_103), .Q (p_r[7]));
  SDFFRHQX1 \datapath_inst_p_i_reg_reg[6] (.RN (n_107), .CK (clk), .D
       (n_104), .SI (p_i[6]), .SE (n_105), .Q (p_i[6]));
  SDFFRHQX1 \datapath_inst_p_r_reg_reg[6] (.RN (n_107), .CK (clk), .D
       (n_104), .SI (p_r[6]), .SE (n_103), .Q (p_r[6]));
  OAI21X1 g2253__2398(.A0 (n_101), .A1 (n_100), .B0 (n_102), .Y
       (n_106));
  NAND2XL g2254__5107(.A (n_101), .B (n_100), .Y (n_102));
  ADDFXL g2255__6260(.A (datapath_inst_pp1[6]), .B (n_11), .CI (n_98),
       .CO (n_100), .S (n_104));
  SDFFRHQX1 \datapath_inst_p_i_reg_reg[5] (.RN (n_107), .CK (clk), .D
       (n_99), .SI (p_i[5]), .SE (n_105), .Q (p_i[5]));
  SDFFRHQX1 \datapath_inst_p_r_reg_reg[5] (.RN (n_107), .CK (clk), .D
       (n_99), .SI (p_r[5]), .SE (n_103), .Q (p_r[5]));
  ADDFX1 g2258__4319(.A (n_12), .B (datapath_inst_pp1[5]), .CI (n_95),
       .CO (n_98), .S (n_99));
  SDFFRHQX1 \datapath_inst_p_i_reg_reg[4] (.RN (n_107), .CK (clk), .D
       (n_97), .SI (p_i[4]), .SE (n_105), .Q (p_i[4]));
  SDFFRHQX1 \datapath_inst_p_r_reg_reg[4] (.RN (n_107), .CK (clk), .D
       (n_97), .SI (p_r[4]), .SE (n_103), .Q (p_r[4]));
  SDFFRHQX1 \datapath_inst_pp1_reg[5] (.RN (n_107), .CK (clk), .D
       (n_96), .SI (datapath_inst_pp1[5]), .SE (n_94), .Q
       (datapath_inst_pp1[5]));
  SDFFRHQX1 \datapath_inst_pp2_reg[5] (.RN (n_107), .CK (clk), .D
       (datapath_inst_pp2[5]), .SI (n_96), .SE (n_92), .Q
       (datapath_inst_pp2[5]));
  ADDFX1 g2269__8428(.A (n_14), .B (datapath_inst_pp1[4]), .CI (n_85),
       .CO (n_95), .S (n_97));
  SDFFRHQX1 \datapath_inst_pp1_reg[6] (.RN (n_107), .CK (clk), .D
       (n_93), .SI (datapath_inst_pp1[6]), .SE (n_94), .Q
       (datapath_inst_pp1[6]));
  SDFFRHQX1 \datapath_inst_pp2_reg[6] (.RN (n_107), .CK (clk), .D
       (datapath_inst_pp2[6]), .SI (n_93), .SE (n_92), .Q
       (datapath_inst_pp2[6]));
  SDFFRHQX1 \datapath_inst_pp1_reg[4] (.RN (n_107), .CK (clk), .D
       (n_91), .SI (datapath_inst_pp1[4]), .SE (n_94), .Q
       (datapath_inst_pp1[4]));
  SDFFRHQX1 \datapath_inst_pp2_reg[4] (.RN (n_107), .CK (clk), .D
       (datapath_inst_pp2[4]), .SI (n_91), .SE (n_92), .Q
       (datapath_inst_pp2[4]));
  SDFFRHQX1 \datapath_inst_p_r_reg_reg[3] (.RN (n_107), .CK (clk), .D
       (n_90), .SI (p_r[3]), .SE (n_103), .Q (p_r[3]));
  SDFFRHQX1 \datapath_inst_p_i_reg_reg[3] (.RN (n_107), .CK (clk), .D
       (n_90), .SI (p_i[3]), .SE (n_105), .Q (p_i[3]));
  OAI21X1 g2272__5526(.A0 (n_87), .A1 (n_86), .B0 (n_88), .Y (n_96));
  SDFFRHQX1 \datapath_inst_pp1_reg[7] (.RN (n_107), .CK (clk), .D
       (n_89), .SI (datapath_inst_pp1[7]), .SE (n_94), .Q
       (datapath_inst_pp1[7]));
  CLKXOR2X1 g2273__6783(.A (n_57), .B (n_83), .Y (n_93));
  SDFFRHQX1 \datapath_inst_pp2_reg[7] (.RN (n_107), .CK (clk), .D
       (datapath_inst_pp2[7]), .SI (n_89), .SE (n_92), .Q
       (datapath_inst_pp2[7]));
  NAND2XL g2275__3680(.A (n_87), .B (n_86), .Y (n_88));
  ADDFX1 g2281__1617(.A (n_16), .B (datapath_inst_pp1[3]), .CI (n_73),
       .CO (n_85), .S (n_90));
  OAI21X1 g2280__2802(.A0 (n_82), .A1 (n_80), .B0 (n_81), .Y (n_91));
  SDFFRHQX1 \datapath_inst_pp1_reg[3] (.RN (n_107), .CK (clk), .D
       (n_84), .SI (datapath_inst_pp1[3]), .SE (n_94), .Q
       (datapath_inst_pp1[3]));
  SDFFRHQX1 \datapath_inst_pp2_reg[3] (.RN (n_107), .CK (clk), .D
       (datapath_inst_pp2[3]), .SI (n_84), .SE (n_92), .Q
       (datapath_inst_pp2[3]));
  AOI21X1 g2277__1705(.A0 (n_74), .A1 (n_82), .B0 (n_79), .Y (n_83));
  OAI2BB1X1 g2278__5122(.A0N (n_82), .A1N (n_72), .B0 (n_76), .Y
       (n_86));
  NAND2XL g2283__8246(.A (n_82), .B (n_80), .Y (n_81));
  OAI2BB1X1 g2279__7098(.A0N (n_55), .A1N (n_79), .B0 (n_56), .Y
       (n_89));
  SDFFRHQX1 \datapath_inst_p_i_reg_reg[2] (.RN (n_107), .CK (clk), .D
       (n_78), .SI (p_i[2]), .SE (n_105), .Q (p_i[2]));
  SDFFRHQX1 \datapath_inst_p_r_reg_reg[2] (.RN (n_107), .CK (clk), .D
       (n_78), .SI (p_r[2]), .SE (n_103), .Q (p_r[2]));
  ADDFX1 g2285__6131(.A (n_60), .B (n_46), .CI (n_65), .CO (n_82), .S
       (n_84));
  SDFFRHQX1 \datapath_inst_pp2_reg[2] (.RN (n_107), .CK (clk), .D
       (datapath_inst_pp2[2]), .SI (n_77), .SE (n_92), .Q
       (datapath_inst_pp2[2]));
  SDFFRHQX1 \datapath_inst_pp1_reg[2] (.RN (n_107), .CK (clk), .D
       (n_77), .SI (datapath_inst_pp1[2]), .SE (n_94), .Q
       (datapath_inst_pp1[2]));
  AOI21X1 g2287__1881(.A0 (n_75), .A1 (n_76), .B0 (n_71), .Y (n_79));
  NAND2XL g2290__5115(.A (n_75), .B (n_74), .Y (n_87));
  ADDFX1 g2291__7482(.A (n_15), .B (datapath_inst_pp1[2]), .CI (n_61),
       .CO (n_73), .S (n_78));
  NAND2XL g2289__4733(.A (n_76), .B (n_72), .Y (n_80));
  CLKINVX1 g2295(.A (n_71), .Y (n_74));
  SDFFRHQX1 \datapath_inst_p_i_reg_reg[1] (.RN (n_107), .CK (clk), .D
       (n_70), .SI (p_i[1]), .SE (n_105), .Q (p_i[1]));
  SDFFRHQX1 \datapath_inst_p_r_reg_reg[1] (.RN (n_107), .CK (clk), .D
       (n_70), .SI (p_r[1]), .SE (n_103), .Q (p_r[1]));
  NAND2XL g2294__6161(.A (n_67), .B (n_66), .Y (n_76));
  NOR2XL g2298__9315(.A (n_69), .B (n_68), .Y (n_71));
  NAND2XL g2297__9945(.A (n_69), .B (n_68), .Y (n_75));
  OR2X1 g2296__2883(.A (n_67), .B (n_66), .Y (n_72));
  OAI21X1 g2300__2346(.A0 (n_63), .A1 (n_62), .B0 (n_64), .Y (n_77));
  ADDFXL g2303__1666(.A (n_37), .B (n_25), .CI (n_48), .CO (n_67), .S
       (n_65));
  ADDFXL g2299__7410(.A (n_27), .B (n_47), .CI (n_44), .CO (n_68), .S
       (n_66));
  NAND2XL g2301__6417(.A (n_63), .B (n_62), .Y (n_64));
  ADDFX1 g2304__5477(.A (n_13), .B (datapath_inst_pp1[1]), .CI (n_43),
       .CO (n_61), .S (n_70));
  OA21X1 g2311__2398(.A0 (n_54), .A1 (n_53), .B0 (n_59), .Y (n_62));
  SDFFRHQX1 \datapath_inst_pp2_reg[1] (.RN (n_107), .CK (clk), .D
       (datapath_inst_pp2[1]), .SI (n_58), .SE (n_92), .Q
       (datapath_inst_pp2[1]));
  NAND2XL g2302__5107(.A (n_63), .B (n_59), .Y (n_60));
  SDFFRHQX1 \datapath_inst_pp1_reg[1] (.RN (n_107), .CK (clk), .D
       (n_58), .SI (datapath_inst_pp1[1]), .SE (n_94), .Q
       (datapath_inst_pp1[1]));
  OAI21X1 g2310__6260(.A0 (n_50), .A1 (n_49), .B0 (n_51), .Y (n_69));
  NAND2XL g2309__4319(.A (n_56), .B (n_55), .Y (n_57));
  NAND2XL g2314__8428(.A (n_54), .B (n_53), .Y (n_59));
  SDFFRHQX1 \datapath_inst_p_i_reg_reg[0] (.RN (n_107), .CK (clk), .D
       (n_52), .SI (p_i[0]), .SE (n_105), .Q (p_i[0]));
  SDFFRHQX1 \datapath_inst_p_r_reg_reg[0] (.RN (n_107), .CK (clk), .D
       (n_52), .SI (p_r[0]), .SE (n_103), .Q (p_r[0]));
  NAND2XL g2312__5526(.A (n_50), .B (n_49), .Y (n_51));
  ADDHX1 g2317__6783(.A (n_24), .B (n_35), .CO (n_47), .S (n_48));
  ADDHXL g2315__3680(.A (n_33), .B (n_30), .CO (n_46), .S (n_53));
  SDFFRHQX1 \datapath_inst_pp1_reg[0] (.RN (n_107), .CK (clk), .D
       (n_45), .SI (datapath_inst_pp1[0]), .SE (n_94), .Q
       (datapath_inst_pp1[0]));
  OAI21X1 g2313__1617(.A0 (n_23), .A1 (n_26), .B0 (n_50), .Y (n_55));
  AND2X1 g2320__2802(.A (n_38), .B (n_63), .Y (n_58));
  SDFFRHQX1 \datapath_inst_pp2_reg[0] (.RN (n_107), .CK (clk), .D
       (datapath_inst_pp2[0]), .SI (n_45), .SE (n_92), .Q
       (datapath_inst_pp2[0]));
  CLKXOR2X1 g2321__1705(.A (n_41), .B (n_42), .Y (n_49));
  CLKXOR2X1 g2322__5122(.A (n_39), .B (n_40), .Y (n_44));
  ADDFX1 g2316__8246(.A (n_17), .B (datapath_inst_pp1[0]), .CI (n_18),
       .CO (n_43), .S (n_52));
  NAND2XL g2323__7098(.A (n_42), .B (n_41), .Y (n_56));
  NAND2XL g2326__6131(.A (n_40), .B (n_39), .Y (n_50));
  NAND2XL g2324__1881(.A (n_45), .B (n_54), .Y (n_63));
  OAI22X1 g2325__5115(.A0 (n_29), .A1 (n_34), .B0 (n_36), .B1 (n_31),
       .Y (n_38));
  NOR2XL g2333__7482(.A (n_36), .B (n_28), .Y (n_37));
  NOR2XL g2328__4733(.A (n_32), .B (n_34), .Y (n_35));
  NOR2XL g2329__6161(.A (n_32), .B (n_31), .Y (n_33));
  NOR2XL g2330__9315(.A (n_29), .B (n_28), .Y (n_30));
  NOR2XL g2331__9945(.A (n_36), .B (n_26), .Y (n_27));
  NOR2XL g2332__2883(.A (n_29), .B (n_26), .Y (n_25));
  NOR2XL g2327__2346(.A (n_23), .B (n_31), .Y (n_24));
  NOR2XL g2340__1666(.A (n_32), .B (n_28), .Y (n_39));
  NOR2XL g2335__7410(.A (n_23), .B (n_34), .Y (n_40));
  OAI21X1 g2334__6417(.A0 (datapath_inst_pp1[7]), .A1 (n_21), .B0
       (n_22), .Y (n_101));
  NOR2XL g2337__5477(.A (n_32), .B (n_26), .Y (n_41));
  NOR2XL g2339__2398(.A (n_23), .B (n_28), .Y (n_42));
  NOR2XL g2338__5107(.A (n_36), .B (n_34), .Y (n_54));
  NOR2XL g2336__6260(.A (n_29), .B (n_31), .Y (n_45));
  DFFRHQX1 \fsm_inst_current_state_reg[0] (.RN (n_107), .CK (clk), .D
       (n_19), .Q (fsm_inst_current_state[0]));
  NAND2XL g2341__4319(.A (datapath_inst_pp1[7]), .B (n_21), .Y (n_22));
  MXI2XL g2342__8428(.A (a_r[2]), .B (a_i[2]), .S0 (n_92), .Y (n_32));
  MXI2XL g2343__5526(.A (a_r[0]), .B (a_i[0]), .S0 (n_92), .Y (n_29));
  MXI2XL g2344__6783(.A (a_r[3]), .B (a_i[3]), .S0 (n_92), .Y (n_23));
  MXI2XL g2348__3680(.A (a_r[1]), .B (a_i[1]), .S0 (n_92), .Y (n_36));
  MXI2XL g2347__1617(.A (b_i[2]), .B (b_r[2]), .S0 (n_20), .Y (n_28));
  MXI2XL g2346__2802(.A (b_i[3]), .B (b_r[3]), .S0 (n_20), .Y (n_26));
  MXI2XL g2349__1705(.A (b_i[0]), .B (b_r[0]), .S0 (n_20), .Y (n_31));
  MXI2XL g2350__5122(.A (b_i[1]), .B (b_r[1]), .S0 (n_20), .Y (n_34));
  DFFRHQX1 \fsm_inst_current_state_reg[2] (.RN (n_107), .CK (clk), .D
       (n_9), .Q (fsm_inst_current_state[2]));
  OAI2BB1XL g2351__8246(.A0N (start), .A1N (n_2), .B0 (n_20), .Y
       (n_19));
  MXI2XL g2360__7098(.A (n_103), .B (n_17), .S0 (datapath_inst_pp2[0]),
       .Y (n_18));
  MXI2XL g2359__6131(.A (n_103), .B (n_17), .S0 (datapath_inst_pp2[3]),
       .Y (n_16));
  MXI2XL g2358__1881(.A (n_103), .B (n_17), .S0 (datapath_inst_pp2[2]),
       .Y (n_15));
  MXI2XL g2352__5115(.A (n_103), .B (n_17), .S0 (datapath_inst_pp2[4]),
       .Y (n_14));
  MXI2XL g2356__7482(.A (n_103), .B (n_17), .S0 (datapath_inst_pp2[1]),
       .Y (n_13));
  MXI2XL g2354__4733(.A (n_103), .B (n_17), .S0 (datapath_inst_pp2[5]),
       .Y (n_12));
  MXI2XL g2357__6161(.A (n_103), .B (n_17), .S0 (datapath_inst_pp2[6]),
       .Y (n_11));
  MXI2XL g2353__9315(.A (n_103), .B (n_17), .S0 (datapath_inst_pp2[7]),
       .Y (n_21));
  NOR2XL g2362__9945(.A (n_10), .B (n_7), .Y (n_20));
  AO22X1 g2365__2883(.A0 (n_8), .A1 (n_10), .B0
       (fsm_inst_current_state[0]), .B1 (n_1), .Y (n_92));
  OAI211XL g2363__2346(.A0 (n_8), .A1 (fsm_inst_current_state[0]), .B0
       (n_4), .C0 (n_103), .Y (n_9));
  DFFRHQX1 \fsm_inst_current_state_reg[1] (.RN (n_107), .CK (clk), .D
       (n_6), .Q (fsm_inst_current_state[1]));
  AOI21X1 g2364__1666(.A0 (n_8), .A1 (n_5), .B0 (n_7), .Y (n_94));
  NAND2XL g2367__7410(.A (fsm_inst_current_state[2]), .B (n_10), .Y
       (n_105));
  CLKINVX1 g2368(.A (n_103), .Y (n_17));
  OR2XL g2369__6417(.A (n_5), .B (n_10), .Y (n_6));
  NOR2XL g2366__5477(.A (fsm_inst_current_state[0]), .B (n_4), .Y
       (n_7));
  NOR3XL g2370__2398(.A (n_2), .B (n_0), .C (n_8), .Y (done));
  INVXL g2372(.A (n_4), .Y (n_1));
  OR3X1 g2371__5107(.A (fsm_inst_current_state[2]), .B (n_0), .C (n_2),
       .Y (n_103));
  NOR2XL g2374__6260(.A (fsm_inst_current_state[1]), .B (n_2), .Y
       (n_5));
  NAND2XL g2373__4319(.A (fsm_inst_current_state[2]), .B (n_0), .Y
       (n_4));
  NOR2XL g2375__8428(.A (fsm_inst_current_state[0]), .B (n_0), .Y
       (n_10));
  CLKINVX1 g2376(.A (fsm_inst_current_state[1]), .Y (n_0));
  INVXL g2378(.A (rst), .Y (n_107));
  CLKINVX1 g2377(.A (fsm_inst_current_state[2]), .Y (n_8));
  CLKINVX1 g2379(.A (fsm_inst_current_state[0]), .Y (n_2));
endmodule

